import type { Metadata } from "next";
import { ReactNode } from "react";
import { BodyLayout } from "~/feat/ui/BodyLayout";
import { Header } from "~/feat/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ArticleLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
          integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
          crossOrigin="anonymous"
        />
      </head>
      <BodyLayout
        className=""
        header={
          <Header
            topics={[
              { text: "Home", link: "/", emphasized: false },
              { text: "Article", link: "./", emphasized: true },
            ]}
          />
        }
      >
        ** THIS IS ARTICLE ROUTING GROUP **
        {children}
      </BodyLayout>
    </>
  );
}
