on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Activate pnpm
        id: pnpm-config
        run: corepack pnpm --version && echo "STORE_PATH=$(corepack pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Prepare dependencies
        run: corepack pnpm i

      - name: Run check
        run: corepack pnpm run ci
