on:
  workflow_dispatch:

permissions:
  contents: write

name: Deploy the blog with the latest articles data

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          git config user.name "GitHub Action"
          git config user.email "github-blog-ga@f4n.dev"

      - run: |
          git fetch
          git checkout production
          git reset --hard main

      - run: |
          git submodule update --init --recursive --remote

      - run: |
          git add .
          git status
          git commit -m "🍱 Update the branch to the latest"

      - run: git push origin production --force-with-lease
